using System;
using UnityEngine;

public class loot : MonoBehaviour
{
    public itemSO itemSO;
    public SpriteRenderer sr;
    public Animator anim;

    public int quantity;
    public static event Action<itemSO, int> onLootPickUp;

    private void OnValidate()
    {
        if(itemSO == null)
            return;

        sr.sprite = itemSO.itemIcon;
        this.name = itemSO.itemName;
    }

    private void OnTriggerEnter2D(Collider2D collision)
    {
        if(collision.CompareTag("Player"))
        {
            anim.Play("othersLootPickUp");
            onLootPickUp?.Invoke(itemSO, quantity);
            Destroy(gameObject, 0.5f);
        }
    }
}
